atease/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.urls import include
from mainapp import views
app_name = "mainapp"

urlpatterns = [
	path('', views.mainpage, name='mainpage'),
	path('account/login/', views.login, name='login'),
	path('account/logout/', views.logout, name='logout'),
	path('account/forgetpassword/', views.forgetpassword, name='forgetpassword'),
	path('account/signup/', views.signup, name='signup'),
	path('profile/patient/', views.patient_profile, name='patient_profile'),
	path('profile/doctor/', views.doctor_profile, name='doctor_profile'),
	path('profile/nurse/', views.nurse_profile, name='nurse_profile'),
	path('profile/receptionist/', views.receptionist_profile, name='receptionist_profile'),
	path('profile/', views.create_profile, name='create_profile'),
	path('gp_view/', views.gp_view, name='gp_view'),
	path('staff_only/<slug:patient_id>/', views.patient_view, name='patient_view'),
	path('verify/<slug:code>/', views.verify_view, name='verify_view'),
]

mainapp/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models
import jsonfield

class GeneralPractice(models.Model):
	name = models.CharField(max_length=32)
	registration_number = models.CharField(max_length=32)
	address = jsonfield.JSONField()
	contact_number = models.CharField(max_length=32)
	open_times = jsonfield.JSONField()

	class Meta:
		verbose_name_plural = "GeneralPractice"

	def __str__(self):
		return self.name

class Patient(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	date_of_birth = models.DateField() 
	address = jsonfield.JSONField()
	mobile = models.CharField(max_length=32)
	nhs_number = models.CharField(max_length=32)
	blood_group = models.CharField(max_length=32)
	patient_at = models.ForeignKey(GeneralPractice, on_delete=models.CASCADE)
	email_verified = models.BooleanField(default=False, blank=True)
	verification_data = jsonfield.JSONField()

	class Meta:
		verbose_name_plural = "Patient"

	def __str__(self):
		return self.user.get_full_name()

class Doctor(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	works_at = models.ForeignKey(GeneralPractice, on_delete=models.CASCADE)
	working_hours = jsonfield.JSONField()
	email_verified = models.BooleanField(default=False, blank=True)
	verification_data = jsonfield.JSONField()

	class Meta:
		verbose_name_plural = "Doctor"

class Nurse(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	works_at = models.ForeignKey(GeneralPractice, on_delete=models.CASCADE)
	working_hours = jsonfield.JSONField()
	email_verified = models.BooleanField(default=False, blank=True)
	verification_data = jsonfield.JSONField()

	class Meta:
		verbose_name_plural = "Nurse"

class Receptionist(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	works_at = models.ForeignKey(GeneralPractice, on_delete=models.CASCADE)
	working_hours = jsonfield.JSONField()
	email_verified = models.BooleanField(default=False, blank=True)
	verification_data = jsonfield.JSONField()

	class Meta:
		verbose_name_plural = "Receptionist"

class Appointments(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
	time = models.DateTimeField(null=True, blank=True)

	class Meta:
		verbose_name_plural = "Appointments"

class MyMedicalRecords(models.Model):
	# Used and done.
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	document = models.FileField(upload_to='myMedicalRecords/', blank=True, null=True,)

	class Meta:
		verbose_name_plural = "MyMedicalRecords"

class GPMedicalRecords(models.Model):
	# Used by staff to upload doc to the patient
	prescribed_to = models.ForeignKey(Patient, on_delete=models.CASCADE)
	prescribed_by = models.ForeignKey(Doctor, on_delete=models.CASCADE)
	document = models.FileField(upload_to='gpMedicalRecords/', blank=True, null=True,)
	access_to_patient = models.BooleanField(default=False)

	class Meta:
		verbose_name_plural = "GPMedicalRecords"

class GPCurrentMedication(models.Model):
	prescribed_to = models.ForeignKey(Patient, on_delete=models.CASCADE)
	prescribed_by = models.ForeignKey(Doctor, on_delete=models.CASCADE)
	name = models.CharField(max_length=32)
	description = models.TextField()
	start_date = models.DateField()
	prescribed_date = models.DateField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "GPCurrentMedication"

class Notes(models.Model):
	# Used by the patients
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=32)
	description = models.TextField()
	date = models.DateTimeField(auto_now_add=True, blank=True)

	class Meta:
		verbose_name_plural = "Notes"

class MyCurrentMedication(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=32)
	description = models.TextField()
	start_date = models.DateField()

	class Meta:
		verbose_name_plural = "MyCurrentMedication"

class Countries(models.Model):
	alpha = models.CharField(max_length=4)
	name = models.CharField(max_length=64)

	class Meta:
		verbose_name_plural = "Countries"
		ordering = ('name',)

	def __str__ (self):
		return str(self.id) + " - " + self.alpha + " - " + self.name

class HealthAdvice(models.Model):
	title = models.CharField(max_length=64)
	fact = models.TextField()
	symptoms = models.TextField()

	class Meta:
		verbose_name_plural = "HealthAdvice"

mainapp/forms.py
from django import forms

class MyMedicalRecordsForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 20 megabytes'
    )

class GPMedicalRecordsForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 20 megabytes'
    )

mainapp/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import serializers
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from http import HTTPStatus
from mainapp.forms import GPMedicalRecordsForm
from mainapp.forms import MyMedicalRecordsForm
from mainapp.models import Appointments
from mainapp.models import Countries
from mainapp.models import Doctor
from mainapp.models import GPCurrentMedication
from mainapp.models import GPMedicalRecords
from mainapp.models import GeneralPractice
from mainapp.models import HealthAdvice
from mainapp.models import MyCurrentMedication
from mainapp.models import MyMedicalRecords
from mainapp.models import Notes
from mainapp.models import Nurse
from mainapp.models import Patient
from mainapp.models import Receptionist
from mainapp.utils import install_countries
from mainapp.utils import install_gp
from mainapp.utils import install_patients
import datetime
import json
import pandas as pd
import uuid

def login(request):

	if request.method == 'POST' and 'LOGIN' in request.POST:
		username = request.POST['email']
		password = request.POST['password']

		if not request.POST.get('user_remember', None):
			request.session.set_expiry(0)

		user = authenticate(username=username, password=password)
		if user:
			auth_login(request, user)
			return redirect('mainapp:mainpage')
		else:
			context = {
				"message": "Username or Password did not match!",
			}
			return render(request,"mainapp/login.html", context)

	return render(request,"mainapp/login.html", {})

def logout(request):
	auth_logout(request)
	return redirect('mainapp:login')

def forgetpassword(request):
	return render(request,"mainapp/forgetpassword.html", {})

def signup(request):

	if request.method == 'POST' and 'SIGNUP' in request.POST:
		firstname = request.POST['first_name']
		lastname = request.POST['last_name']
		email = request.POST['email']
		password = request.POST['password']

		if User.objects.filter(username=email).exists():
			context = {
				"message": "An account already exists for this email address!",
				"email": email,
				"firstname": firstname,
				"lastname": lastname
			}
			return render(request,"mainapp/signup.html", context)
		else:
			if(len(password)<8 or any(letter.isalpha() for letter in password)==False or any(capital.isupper() for capital in password)==False or any(number.isdigit() for number in password)==False):
				context = {
					"message": "Your password is not strong enough.",
					"email": email,
					"firstname": firstname,
					"lastname": lastname
				}
				return render(request,"mainapp/signup.html", context)

			user = User.objects.create_user(username=email, email=email, password=password, first_name=firstname, last_name=lastname)
			user.save()

			context = {
				"message": "Account created successfully.",
			}
			return render(request,"mainapp/signup.html", context)

	return render(request,"mainapp/signup.html", {})

def mainpage(request):
	context = {
		"health_advice": HealthAdvice.objects.all()
	}
	return render(request,"mainapp/mainpage.html", context)

@login_required
def create_profile(request):
	if Patient.objects.filter(user=request.user).exists():
		return redirect('mainapp:patient_profile')

	if Doctor.objects.filter(user=request.user).exists():
		return redirect('mainapp:doctor_profile')

	if Nurse.objects.filter(user=request.user).exists():
		return redirect('mainapp:nurse_profile')

	if Receptionist.objects.filter(user=request.user).exists():
		return redirect('mainapp:receptionist_profile')

	if request.is_ajax():
		TASK = request.GET.get('TASK', None)

		if TASK == "search_for_gp":
			gp_code = request.GET.get('gp_code', None)
			get_gps = GeneralPractice.objects.filter(registration_number=gp_code)
			if get_gps.exists():
				gp_object = get_gps[0]
				the_data = {
					"gp_name": gp_object.name,
					"address_1": gp_object.address["address_1"],
					"address_2": gp_object.address["address_2"],
					"city": gp_object.address["city"],
					"postal_zip": gp_object.address["postalZip"],
					"contact_number": gp_object.contact_number,
				}
				return HttpResponse(json.dumps({"found": True, "data": the_data}), content_type="application/json")
			return HttpResponse(json.dumps({"found": False}), content_type="application/json")

	if request.method == "POST" and "patient_profile" in request.POST:
		date_of_birth = request.POST['date_of_birth']
		mobile_number = request.POST['mobile_number']
		nhs_number = request.POST['nhs_number']
		blood_group = request.POST['blood_group']
		gp_code = request.POST['gp_code']

		country = Countries.objects.get(alpha=request.POST["country"])
		location = {
			"address_1": request.POST["address_1"].strip().title(),
			"address_2": request.POST["address_2"].strip().title(),
			"city": request.POST["city"].strip().title(),
			"stateProvince": request.POST["stateProvince"].strip().title(),
			"postalZip": request.POST["postalZip"].strip().upper(),
			"country": {
				"alpha": country.alpha,
				"name": country.name
			}
		}

		the_gp = GeneralPractice.objects.filter(registration_number=gp_code)
		if not the_gp.exists():
			messages.add_message(request,messages.SUCCESS, "No GP found.")
			return redirect('mainapp:create_profile')


		Patient.objects.create(
			user = request.user,
			date_of_birth = date_of_birth,
			address = location,
			mobile = mobile_number,
			nhs_number = nhs_number,
			blood_group = blood_group,
			patient_at = the_gp[0]
		)
		return redirect('mainapp:patient_profile')

	if request.method == "POST" and "staff_profile" in request.POST:
		role = request.POST['role']
		gp_code = request.POST['gp_code_for_staff']
		weekdays = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
		schedule = ['from', 'to']
		workingHours = {}

		the_gp = GeneralPractice.objects.filter(registration_number=gp_code)
		if not the_gp.exists():
			messages.add_message(request,messages.SUCCESS, "No GP found.")
			return redirect('mainapp:create_profile')

		for i in weekdays:
			workingHours[i] = {
				'from': request.POST[i+'_from'],
				'to': request.POST[i+'_to']
			}

		if role == 'doctor':
			print("creating doctor role")
			Doctor.objects.create(
				user = request.user,
				works_at = the_gp[0],
				working_hours = workingHours
			)
			return redirect('mainapp:doctor_profile')
			
		elif role == 'nurse':
			print("creating nurse role")
			Nurse.objects.create(
				user = request.user,
				works_at = the_gp[0],
				working_hours = workingHours
			)

			return redirect('mainapp:nurse_profile')
		elif role == 'receptionist':
			print("creating receptionist role")
			Receptionist.objects.create(
				user = request.user,
				works_at = the_gp[0],
				working_hours = workingHours
			)
			return redirect('mainapp:receptionist_profile')

	context = {
		"countries": Countries.objects.all(),
		"gps": GeneralPractice.objects.all(),
	}
	return render(request,"mainapp/create_profile.html", context)

@login_required
def patient_profile(request):
	try:
		patient = Patient.objects.get(user=request.user)
	except Patient.DoesNotExist:
		raise e

	if request.method == "POST" and "UPDATEPATIENTPROFILE" in request.POST:
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']
		email = request.POST['email']
		mobile = request.POST['mobile']

		patient.mobile = mobile
		patient.user.first_name = first_name
		patient.user.last_name = last_name

		if patient.user.email != email:
			patient.email_verified = False

		patient.user.email = email
		patient.save()
		patient.user.save()
		return redirect('mainapp:patient_profile')

	if request.method == "POST" and "UPDATEPATIENTADDRESS" in request.POST:
		country = Countries.objects.get(alpha=request.POST["country"])
		location = {
			"address_1": request.POST["address_1"].strip().title(),
			"address_2": request.POST["address_2"].strip().title(),
			"city": request.POST["city"].strip().title(),
			"stateProvince": request.POST["stateProvince"].strip().title(),
			"postalZip": request.POST["postalZip"].strip().upper(),
			"country": {
				"alpha": country.alpha,
				"name": country.name
			}
		}
		patient.address = location
		patient.save()
		return redirect('mainapp:patient_profile')

	if request.method == 'POST' and "CREATENOTES" in request.POST:
		title = request.POST["title"]
		description = request.POST["description"]
		Notes.objects.create(
			user = request.user,
			title = title,
			description = description,
		)
		return redirect('mainapp:patient_profile')

	if request.method == 'POST' and "Create_My_Current_Medication" in request.POST:
		name = request.POST['name']
		description = request.POST['description']
		start_date = request.POST['start_date']
		MyCurrentMedication.objects.create(
			user = request.user,
			name = name,
			description = description,
			start_date = start_date,
		)
		return redirect('mainapp:patient_profile')

	# Handle file upload
	if request.method == 'POST' and "UPLOADMYMEDICALRECORDDOCUMENTS" in request.POST:
		form = MyMedicalRecordsForm(request.POST, request.FILES)
		if form.is_valid():
			newdoc = MyMedicalRecords(user=request.user,document = request.FILES['docfile'])
			if newdoc.document.size > 20971520:
				messages.add_message(request,messages.SUCCESS, "File size exceeds max limit.")
			else:
				newdoc.save()
			# Redirect to the document list after POST
			return redirect('mainapp:patient_profile')
	else:
		form = MyMedicalRecordsForm() # A empty, unbound form

	if request.method == 'POST' and "DELETENOTES" in request.POST:
		notes_id = request.POST['notes_id']

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>AtEase</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet" />
		<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.css">
		<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.js"></script>

		<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<a class="navbar-brand" href="#">AtEase</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
					</li>
					{% if user.is_authenticated %}
					<!-- Member -->
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Account
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="{% url 'mainapp:create_profile' %}">Profile</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'mainapp:logout' %}">Logout</a>
						</div>
					</li>
					{% else %}
					<!-- Guest -->
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Login / Register
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="{% url 'mainapp:signup' %}">Register</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'mainapp:login' %}">Login</a>
						</div>
					</li>
					{% endif %}
				</ul>
			</div>
		</nav>
		{% block content %}
		{% endblock %}
	</body>
</html>

mainapp/templates/mainapp/gp_view.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block content %}
<style type="text/css">
	

#custom-search-input {
        margin:0;
        margin-top: 10px;
        padding: 0;
    }
 
    #custom-search-input .search-query {
        padding-right: 3px;
        padding-right: 4px \9;
        padding-left: 3px;
        padding-left: 4px \9;
        /* IE7-8 doesn't have border-radius, so don't indent the padding */
 
        margin-bottom: 0;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
    }
 
    #custom-search-input button {
        border: 0;
        background: none;
        /** belows styles are working good */
        padding: 2px 5px;
        margin-top: 2px;
        position: relative;
        left: -28px;
        /* IE7-8 doesn't have border-radius, so don't indent the padding */
        margin-bottom: 0;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
        color:#D9230F;
    }
 
    .search-query:focus + button {
        z-index: 3;   
    }

</style>
<div class="container">
	<nav>
		<div class="nav nav-tabs" id="nav-tab" role="tablist">
			<a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Patients</a>
			<a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Opening Hours</a>
			<a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</a>
		</div>
	</nav>
	<div class="tab-content" id="nav-tabContent">
		<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
		<br><br>
		<form method="post">
			{% csrf_token %}
			<input type="text" name="search_for_patients" hidden>
			<div class="input-group">
				<input class="form-control py-2 border-right-0 border" type="search" name="patient_name" placeholder="Search for patients" id="example-search-input">
				<span class="input-group-append">
					<input class="input-group-text bg-transparent" type="submit"></input>
				</span>
			</div>
		</form>
		<br>

		{% if patients %}




			<table class="table">
				<thead class="thead-dark">
					<tr>
					<th scope="col">Name</th>
					<th scope="col">Dob</th>
					<th scope="col">Contact</th>
					</tr>
				</thead>
				<tbody>
					{% for p in patients %}
					<tr>
						<td><a href="{% url 'mainapp:patient_view' p.id %}">{{p.user.get_full_name}}</a></td>
					<td>{{p.date_of_birth}}</td>
					<td>{{p.mobile}}</td>
					</tr>
					{% endfor %}

				</tbody>
			</table>

		

		{% endif %}


		</div>
		<div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
			<div style="height:70px;"></div>
			<h3>{{profile.works_at.name}}</h3>
			{% if can_edit_opening_times %}


			<form method="post">
				{% csrf_token %}
				<input type="text" name="Update_GP_Hours" hidden>

				<div class="form-group">
					<h4 for="working_hours">Edit GP Hours</h4>
					<br>
					<div class="row">
						<div class="col-md-auto">
							<div>
								<label>Monday: </label>
								From: <input type="time" name="monday_from" value="{{profile.works_at.open_times.monday.from}}">
								To: <input type="time" name="monday_to" value="{{profile.works_at.open_times.monday.to}}">
							</div>
							<br>
							<div>
								<label>Tuesday: </label>
								From: <input type="time" name="tuesday_from" value="{{profile.works_at.open_times.tuesday.from}}">
								To: <input type="time" name="tuesday_to" value="{{profile.works_at.open_times.tuesday.to}}">
							</div>
							<br>
							<div>
								<label>Wednesday: </label>
								From: <input type="time" name="wednesday_from" value="{{profile.works_at.open_times.wednesday.from}}">
								To: <input type="time" name="wednesday_to" value="{{profile.works_at.open_times.wednesday.to}}">
							</div>
							<br>
							<div>
								<label>Thursday: </label>
								From: <input type="time" name="thursday_from" value="{{profile.works_at.open_times.thursday.from}}">
								To: <input type="time" name="thursday_to" value="{{profile.works_at.open_times.thursday.to}}">
							</div>
							<br>
							<div>
								<label>Friday: </label>
								From: <input type="time" name="friday_from" value="{{profile.works_at.open_times.friday.from}}">
								To: <input type="time" name="friday_to" value="{{profile.works_at.open_times.friday.to}}">
							</div>
						</div>
					</div>
				</div>

				<div class="form-group">
					<button type="submit" class="btn btn-success btn-lg btn-block">Update Hours</button>
				</div>


			</form>



			{% else %}
				<table class="table">
	                <thead class="thead-dark">
	                    <tr>
	                        <th scope="col">Weekday</th>
	                        <th scope="col">Open</th>
	                        <th scope="col">Close</th>
	                    </tr>
	                </thead>
	                <tbody>
	                    <tr>
	                        <td>Monday</td>
	                        <td>{{profile.works_at.open_times.monday.from}}</td>
	                        <td>{{profile.works_at.open_times.monday.to}}</td>
	                    </tr>
	                    <tr>
	                        <td>Tuesday</td>
	                        <td>{{profile.works_at.open_times.tuesday.from}}</td>
	                        <td>{{profile.works_at.open_times.tuesday.to}}</td>
	                    </tr>
	                    <tr>
	                        <td>Wednesday</td>
	                        <td>{{profile.works_at.open_times.wednesday.from}}</td>
	                        <td>{{profile.works_at.open_times.wednesday.to}}</td>
	                    </tr>
	                    <tr>
	                        <td>Thursday</td>
	                        <td>{{profile.works_at.open_times.thursday.from}}</td>
	                        <td>{{profile.works_at.open_times.thursday.to}}</td>
	                    </tr>
	                    <tr>
	                        <td>Friday</td>
	                        <td>{{profile.works_at.open_times.monday.from}}</td>
	                        <td>{{profile.works_at.open_times.monday.to}}</td>
	                    </tr>
	                </tbody>
	            </table>
			{% endif %}
		</div>
		<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">..65.</div>
	</div>
</div>
{% endblock %}

mainapp/templates/mainapp/login.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block content %}
<style type="text/css">
.login-form,.my-form,.nav-link,.navbar-brand{font-family:Raleway,sans-serif}.my-form{padding-top:1.5rem;padding-bottom:1.5rem}.my-form .row{margin-left:0;margin-right:0}.login-form{padding-top:1.5rem;padding-bottom:1.5rem}.login-form .row{margin-left:0;margin-right:0}
</style>
<main class="login-form">
	<div class="cotainer">
		{% if message %}
			<div style="color: black; text-align: center;" class="alert alert-success" role="alert">{{message}}</div>
		{% endif %}
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">Login</div>
					<div class="card-body">
						<form method="post">
							{% csrf_token %}
							<input type="text" name="LOGIN" hidden>
							<div class="form-group row">
								<label for="email_address" class="col-md-4 col-form-label text-md-right">Email</label>
								<div class="col-md-6">
									<input type="text" id="email_address" class="form-control" name="email" required autofocus>
								</div>
							</div>
							<div class="form-group row">
								<label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
								<div class="col-md-6">
									<input type="password" id="password" class="form-control" name="password" required>
								</div>
							</div>
							<div class="form-group row">
								<div class="col-md-6 offset-md-4">
									<div class="checkbox">
										<label>
											<input type="checkbox" name="remember"> Remember Me
										</label>
									</div>
								</div>
							</div>
							<div class="col-md-12 offset-md-4">
								<button type="submit" class="btn btn-primary">Login</button>
								<a href="{% url 'mainapp:forgetpassword' %" class="btn btn-link">Forgot Your Password?</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	</div>
</main>
{% endblock %}